name: Build and Push Docker Image

on:
  push:
    branches:
      - 'minecraft-**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            registry.digitalocean.com/mcbench/gameservers:${{ github.ref_name }}-${{ steps.date.outputs.DATE }}
            registry.digitalocean.com/mcbench/gameservers:${{ github.ref_name }}-latest
          cache-from: type=registry,ref=registry.digitalocean.com/mcbench/gameservers:${{ github.ref_name }}-latest
          cache-to: type=inline
